**Đặng Thành Nhân - MSSV:522H0006 - Lab08**

In [ ]:
#Example01
import pandas as pd
df = pd.DataFrame({'numbers' : [1, 2, 3], 'colors' : ['red', 'white', 'blue']})
print(df)

   number  color
0       1    red
1       2  white
2       3   blue


In [ ]:
#Example02
import pandas as pd
df = pd.DataFrame({'numbers' : [1, 2, 3], 'colors' : ['red', 'white', 'blue']}, columns=['numbers', 'colors'])
print(df)

   numbers colors
0        1    red
1        2  white
2        3   blue


In [ ]:
#Example03
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(5, 3), columns=['N1', 'N2', 'N3'])
print(df)

         N1        N2        N3
0 -0.693204 -0.480296  0.195961
1  0.532668 -0.895289 -0.558928
2 -0.446446  0.704996  0.318595
3  0.008647  1.355765  0.967675
4  1.880575 -0.580709  0.253655


In [ ]:
#Example04
import pandas as pd
df = pd.DataFrame({'N1' : [1, 2, 3, 4], 'N2' : [4, 3, 2, 1]})
print(df)

   N1  N2
0   1   4
1   2   3
2   3   2
3   4   1


In [ ]:
#Example05
import pandas as pd
L = [{'Name' : 'John', 'Last Name' : 'Smith'}, {'Name' : 'Mary', 'Last Name' : 'Wood'}]
df = pd.DataFrame(L)
print(df)

   Name Last Name
0  John     Smith
1  Mary      Wood


In [ ]:
#Example06
from google.colab import files
uploaded = files.upload()

data = np.loadtxt("sample.txt", delimiter=',')
print(data)

Saving sample.txt to sample (1).txt
[[1.  2.1 0.1]
 [2.  4.5 9. ]
 [3.  5.5 2.1]
 [4.  2.3 3.3]
 [5.  7.7 8.8]]


In [ ]:
#Example07
import pandas as pd

data = pd.read_csv("sample.txt", delimiter=',')
print(data)

   1   2.1   0.1
0  2   4.5   9.0
1  3   5.5   2.1
2  4   2.3   3.3
3  5   7.7   8.8


In [ ]:
#Example08
import pandas as pd

data = pd.read_csv("sample1.txt", delimiter=',')
print(data)
print("Print column Score")
print(data.Score)

   ID  Weight  Score
0   1     2.1    0.1
1   2     4.5    9.0
2   3     5.5    2.1
3   4     2.3    3.3
4   5     7.7    8.8
Print column Score
0    0.1
1    9.0
2    2.1
3    3.3
4    8.8
Name: Score, dtype: float64


In [ ]:
#Example09
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(10, 3), columns=['N1', 'N2', 'N3'])
print(df)
df.head(5)
df.tail(5)
print(df['N2'])

print(df[['N1','N2']])
print(df[1:-2])


         N1        N2        N3
0  1.336182 -0.758282  1.470743
1 -1.738231  1.031590 -0.835607
2  0.209300  0.177432 -0.914084
3 -0.540917  0.630027 -0.102256
4  1.177570  1.329648  1.366194
5 -1.748684 -0.666301 -0.020673
6  1.442009 -0.952156  2.131227
7  0.077260  0.825080  0.566750
8  0.638049 -0.897787  0.347410
9 -0.949669  0.705147  0.993956
0   -0.758282
1    1.031590
2    0.177432
3    0.630027
4    1.329648
5   -0.666301
6   -0.952156
7    0.825080
8   -0.897787
9    0.705147
Name: N2, dtype: float64
         N1        N2
0  1.336182 -0.758282
1 -1.738231  1.031590
2  0.209300  0.177432
3 -0.540917  0.630027
4  1.177570  1.329648
5 -1.748684 -0.666301
6  1.442009 -0.952156
7  0.077260  0.825080
8  0.638049 -0.897787
9 -0.949669  0.705147
         N1        N2        N3
1 -1.738231  1.031590 -0.835607
2  0.209300  0.177432 -0.914084
3 -0.540917  0.630027 -0.102256
4  1.177570  1.329648  1.366194
5 -1.748684 -0.666301 -0.020673
6  1.442009 -0.952156  2.131227
7  0.077260  0.82

In [ ]:
#Exercise01
import pandas as pd

# Define functions to calculate mean and std
def mean(data):
    return sum(data) / len(data)

def std(data):
    mu = mean(data)
    variances = [(x - mu)**2 for x in data]
    return (sum(variances) / len(variances))**0.5

iris_data = pd.read_csv('iris.csv')
# first 5 data points
first_5_data = iris_data.head()
print(first_5_data)
# (count)
count = len(iris_data)

# Calculate mean for each column
mean_sepal_length = mean(iris_data['sepal_length'])
mean_sepal_width = mean(iris_data['sepal_width'])
mean_petal_length = mean(iris_data['petal_length'])
mean_petal_width = mean(iris_data['petal_width'])

#standard deviation
std_sepal_length = std(iris_data['sepal_length'])
std_sepal_width = std(iris_data['sepal_width'])
std_petal_length = std(iris_data['petal_length'])
std_petal_width = std(iris_data['petal_width'])

# minimu
min_sepal_length = iris_data['sepal_length'].min()
min_sepal_width = iris_data['sepal_width'].min()
min_petal_length = iris_data['petal_length'].min()
min_petal_width = iris_data['petal_width'].min()

#maximum
max_sepal_length = iris_data['sepal_length'].max()
max_sepal_width = iris_data['sepal_width'].max()
max_petal_length = iris_data['petal_length'].max()
max_petal_width = iris_data['petal_width'].max()

result_df = pd.DataFrame({
    'sepal_length': [count,mean_sepal_length,
                    std_sepal_length, min_sepal_length, max_sepal_length],
    'sepal_width': [count, mean_sepal_width,
                    std_sepal_width, min_sepal_width, max_sepal_width],
    'petal_length': [count, mean_petal_length,
                    std_petal_length, min_petal_length, max_petal_length],
    'petal_width': [count, mean_petal_width,
                   std_petal_width, min_petal_width, max_petal_width]
}, index=['count', 'mean', 'std', 'min', 'max'])
print(result_df)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.825301     0.432147      1.758529     0.760613
min        4.300000     2.000000      1.000000     0.100000
max        7.900000     4.400000      6.900000     2.500000


In [89]:
#Exercise02
import pandas as pd
import numpy as np

# read data from population.csv file
data = pd.read_csv("population.csv", delimiter=",")
df = pd.DataFrame(data)

# get the first 5 data points
first_5_data_points = df.head(5)

print(first_5_data_points, "\n\n")

# group the data by year then compute the requirements
dt = df.groupby(["Country Name", "Country Code"]).agg(
    {"Year": ["count", "mean", "std", "min", "max"]}
)

# print the result to the screen
print(dt)

  Country Name Country Code  Year      Value
0   Arab World          ARB  1960   92197753
1   Arab World          ARB  1961   94724510
2   Arab World          ARB  1962   97334442
3   Arab World          ARB  1963  100034179
4   Arab World          ARB  1964  102832760 


                                 Year                               
                                count    mean        std   min   max
Country Name       Country Code                                     
Afghanistan        AFG             59  1989.0  17.175564  1960  2018
Albania            ALB             59  1989.0  17.175564  1960  2018
Algeria            DZA             59  1989.0  17.175564  1960  2018
American Samoa     ASM             59  1989.0  17.175564  1960  2018
Andorra            AND             59  1989.0  17.175564  1960  2018
...                               ...     ...        ...   ...   ...
West Bank and Gaza PSE             29  2004.0   8.514693  1990  2018
World              WLD             59